
package clientDemo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Weather", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Weather {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "forecast", targetNamespace = "http://server/", className = "client.Forecast")
    @ResponseWrapper(localName = "forecastResponse", targetNamespace = "http://server/", className = "client.ForecastResponse")
    @Action(input = "http://server/Weather/forecastRequest", output = "http://server/Weather/forecastResponse")
    public String forecast(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
