
package insulinClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsulinDoseCalculatorClassService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8081/qcs?wsdl")
public class InsulinDoseCalculatorClassService
    extends Service
{

    private final static URL INSULINDOSECALCULATORCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSULINDOSECALCULATORCLASSSERVICE_EXCEPTION;
    private final static QName INSULINDOSECALCULATORCLASSSERVICE_QNAME = new QName("http://server/", "InsulinDoseCalculatorClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/qcs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSULINDOSECALCULATORCLASSSERVICE_WSDL_LOCATION = url;
        INSULINDOSECALCULATORCLASSSERVICE_EXCEPTION = e;
    }

    public InsulinDoseCalculatorClassService() {
        super(__getWsdlLocation(), INSULINDOSECALCULATORCLASSSERVICE_QNAME);
    }

    public InsulinDoseCalculatorClassService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSULINDOSECALCULATORCLASSSERVICE_QNAME, features);
    }

    public InsulinDoseCalculatorClassService(URL wsdlLocation) {
        super(wsdlLocation, INSULINDOSECALCULATORCLASSSERVICE_QNAME);
    }

    public InsulinDoseCalculatorClassService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSULINDOSECALCULATORCLASSSERVICE_QNAME, features);
    }

    public InsulinDoseCalculatorClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsulinDoseCalculatorClassService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InsulinDoseCalculatorClass
     */
    @WebEndpoint(name = "InsulinDoseCalculatorClassPort")
    public InsulinDoseCalculatorClass getInsulinDoseCalculatorClassPort() {
        return super.getPort(new QName("http://server/", "InsulinDoseCalculatorClassPort"), InsulinDoseCalculatorClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsulinDoseCalculatorClass
     */
    @WebEndpoint(name = "InsulinDoseCalculatorClassPort")
    public InsulinDoseCalculatorClass getInsulinDoseCalculatorClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "InsulinDoseCalculatorClassPort"), InsulinDoseCalculatorClass.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSULINDOSECALCULATORCLASSSERVICE_EXCEPTION!= null) {
            throw INSULINDOSECALCULATORCLASSSERVICE_EXCEPTION;
        }
        return INSULINDOSECALCULATORCLASSSERVICE_WSDL_LOCATION;
    }

}
